### NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

In [1]:
import numpy as np

In [24]:
# Vector addition
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
vector_sum = vector1 + vector2
print("Vector Sum:", vector_sum)

# Matrix addition
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])
matrix_sum = matrix1 + matrix2
print("Matrix Sum:\n", matrix_sum)

Vector Sum: [5 7 9]
Matrix Sum:
 [[ 8 10 12]
 [14 16 18]]


In [28]:
#Scalar Multiplication
#You can multiply a vector or matrix by a scalar:
# Scalar multiplication
scalar = 2
vector = [1,2,3]
vector_scaled = scalar * vector
print("Scaled Vector:", vector_scaled)

matrix=np.array([[1,2],[3,4]])

matrix_scaled = scalar * matrix
print("Scaled Matrix:\n", matrix_scaled)

Scaled Vector: [1, 2, 3, 1, 2, 3]
Scaled Matrix:
 [[2 4]
 [6 8]]


In [34]:
#Element-wise Multiplication
#Element-wise multiplication between vectors or matrices can be done using the * operator:
#Element-wise multiplication
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

elementwise_product = vector1 * vector2
print("Element-wise Product:", elementwise_product)

matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
matrix_product = matrix1 * matrix2
print("Element-wise Matrix Product:\n", matrix_product)

Element-wise Product: [ 4 10 18]
Element-wise Matrix Product:
 [[ 5 12]
 [21 32]]


NumPy Matrix Operations
Here are some of the basic matrix operations provided by NumPy.

Functions-	Descriptions
array() -   creates a matrix
dot()	-   performs matrix multiplication 
transpose()-transposes a matrix 
linalg.inv()-calculates the inverse of a matrix
linalg.det()-calculates the determinant of a matrix
flatten()- 	 transforms a matrix into 1D array

In [13]:
matrix1=np.array([[1,2],[3,4]]) 


matrix2=np.array([[5,6],[7,8]])

#to multipy using dot

result= np.dot(matrix1 ,matrix2)
print("Matrix multipication of 2 vectors :  \n " , result)

Matrix multipication of 2 vector :  
  [[19 22]
 [43 50]]


In [19]:
# Transpose NumPy Matrix
print(matrix1)
transpos = np.transpose(matrix1)
print("Transpose of matrix is")
print(transpos)

[[1 2]
 [3 4]]
Transpose of matrix is
[[1 3]
 [2 4]]


In [20]:
# Inverse of a Matrix using numpy
print(matrix1)
inverse = np.linalg.inv(matrix1)
print(inverse)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Note: If we try to find the inverse of a non-square matrix, we will get an error message: numpy.linalg.linalgerror: Last 2 dimensions of the array must be square

#### Determinant of a Matrix in NumPy
We can find the determinant of a square matrix using the np.linalg.det() function to calculate the determinant of the given matrix.


det(A) = ad - bc

In [22]:
newarray=np.array([[0,1],[1,2]])
detresult=np.linalg.det(newarray)
print(detresult)

-1.0


### Flatten Matrix in NumPy
Flattening a matrix simply means converting a matrix into a 1D array.

To flatten a matrix into a 1-D array we use the array.flatten() function.

In [23]:
# create a 2x3 matrix
matrix1 = np.array([[1, 2, 3], [4, 5, 7]])

result = matrix1.flatten()
print("Flattened 2x3 matrix:", result)

Flattened 2x3 matrix: [1 2 3 4 5 7]


## Eigenvectors, Eigenvalues
Eigenvectors:
Eigenvectors are special vectors that, when a linear transformation is applied to them, do not change their direction. They may get scaled (stretched or compressed) but they do not rotate or change direction.

Example: Imagine pushing a book across a table. If you push it in certain directions, it just slides in that direction without flipping or rotating. These directions are like eigenvectors—they are directions that remain unchanged except for their length.

Eigenvalues:
What They Are: Eigenvalues are the factors by which the eigenvectors are scaled during the transformation. They tell you how much the eigenvector is stretched or compressed.

Example: If you push the book and it moves twice as far as it would normally move, the "2" in this case is like an eigenvalue. It represents the amount by which the eigenvector is stretched.

Mathematical Definition:
In a mathematical sense, if you have a matrix 
A×v=λ×v
where:
A is the matrix representing the transformation,
v is the eigenvector,
λ (lambda) is the eigenvalue.
This equation means that applying the matrix 𝐴
A to the vector 
v only changes the vector's magnitude (by λ) but not its direction.

Eigenvalues and Eigenvectors are the scalar and vector quantities associated with matrices used for linear transformations. The vector that only changes by a scalar factor after applying a transformation is called an eigenvector, and the scalar value attached to the eigenvector is called the eigenvalue.

Eigenvectors are vectors that are associated with a matrix such that when the matrix multiplies the eigenvector, the resulting vector is a scalar multiple of the eigenvector. Eigenvectors are also called characteristic vectors and can only be found for square matrices. They are very useful in solving various problems involving matrices and differential equations

(A-λI)v = 0 where A is given matrix,λ is scalar value,I is identity matrix and 0 is null matrix

In [2]:
import numpy as np
# Example matrix
A = np.array([[4, 2],
              [1, 3]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display results
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [3]:
B = np.array([[6, 2, 1],
              [2, 3, 1],
              [1, 1, 1]])

eigenvalues_B, eigenvectors_B = np.linalg.eig(B)
print("Eigenvalues of B:", eigenvalues_B)
print("Eigenvectors of B:\n", eigenvectors_B)

Eigenvalues of B: [7.28799214 2.13307448 0.57893339]
Eigenvectors of B:
 [[ 0.86643225  0.49742503 -0.0431682 ]
 [ 0.45305757 -0.8195891  -0.35073145]
 [ 0.20984279 -0.28432735  0.9354806 ]]


Function Behavior
When you call np.linalg.eig(B), the function performs a series of computations internally:

Eigenvalues: The function first computes the eigenvalues of the matrix 
𝐵
B. These are the roots of the characteristic equation 
det(𝐵−𝜆𝐼)=0
det(B−λI)=0, where λ represents the eigenvalues.

Eigenvectors: After finding the eigenvalues, the function computes the corresponding eigenvectors. These are the non-zero vectors 
v that satisfy 𝐵𝑣=𝜆𝑣
Bv=λv for each eigenvalue λ.
The function doesn’t rely on what you name these variables—it only returns the outputs in a fixed order:

 1.First, the eigenvalues.
 2.Then, the eigenvectors.

Problem 2: Diagonalization of a Matrix

Given a matrix:

𝐶=(3 1 0 2)
Find its eigenvalues and eigenvectors, then verify if the matrix can be diagonalized.

In [5]:
C = np.array([[3, 1],
              [0, 2]])

eigenvalues_C, eigenvectors_C = np.linalg.eig(C) #C−λI, (C−λI)v=0.
D = np.diag(eigenvalues_C) #Diagonal Matrix Creation:creates a diagonal matrix D using the eigenvalues.
P = eigenvectors_C #Eigenvector Matrix:Each column of P corresponds to an eigenvector of the matrix C.
P_inv = np.linalg.inv(P) #We compute inverse of eigenvector matrixP,This is necessary for the diagonalization process.

# Verify diagonalization
diagonalized_C = P @ D @ P_inv #reconstructs C from its eigenvalues and eigenvectors,C=PDP−1.
print("Eigenvalues of C:", eigenvalues_C)
print("Eigenvectors of C:\n", eigenvectors_C)
print("Diagonalized C:\n", diagonalized_C)



Eigenvalues of C: [3. 2.]
Eigenvectors of C:
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
Diagonalized C:
 [[3. 1.]
 [0. 2.]]


Problem 3: Symmetric Matrix Eigenvalues and Eigenvectors
For a symmetric matrix:

Calculate the eigenvalues and eigenvectors and observe their properties.

In [6]:
D = np.array([[4, -2, 2],
              [-2, 3, -1],
              [2, -1, 3]])

eigenvalues_D, eigenvectors_D = np.linalg.eig(D)
print("Eigenvalues of D:", eigenvalues_D)
print("Eigenvectors of D:\n", eigenvectors_D)

# Check if eigenvectors are orthogonal (should be for a symmetric matrix)
orthogonality_check = np.dot(eigenvectors_D.T, eigenvectors_D) #Orthogonal eigenvectors for symmetric 
#matrices (like D) should result in an identity matrix when dot product of transpose of eigenvector matrix and the eigenvector matrix itself is calculated.
print("Orthogonality check (should be close to identity matrix):\n", orthogonality_check)

Eigenvalues of D: [6.82842712 1.17157288 2.        ]
Eigenvectors of D:
 [[ 7.07106781e-01 -7.07106781e-01 -3.61461177e-16]
 [-5.00000000e-01 -5.00000000e-01  7.07106781e-01]
 [ 5.00000000e-01  5.00000000e-01  7.07106781e-01]]
Orthogonality check (should be close to identity matrix):
 [[ 1.00000000e+00 -1.66533454e-16  8.80288308e-17]
 [-1.66533454e-16  1.00000000e+00  5.22593833e-16]
 [ 8.80288308e-17  5.22593833e-16  1.00000000e+00]]


Problem 4: Eigenvalue Decomposition of a 4x4 Matrix
Find the eigenvalues and eigenvectors and explore the implications of degeneracy (multiple eigenvalues with the same value).

In [7]:
E = np.array([[5, 1, 0, 0],
              [1, 5, 0, 0],
              [0, 0, 4, 2],
              [0, 0, 2, 4]])

eigenvalues_E, eigenvectors_E = np.linalg.eig(E)
print("Eigenvalues of E:", eigenvalues_E)
print("Eigenvectors of E:\n", eigenvectors_E)

Eigenvalues of E: [6. 4. 6. 2.]
Eigenvectors of E:
 [[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.         -0.          0.70710678 -0.70710678]
 [ 0.         -0.          0.70710678  0.70710678]]
