### NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

In [1]:
import numpy as np

In [24]:
# Vector addition
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
vector_sum = vector1 + vector2
print("Vector Sum:", vector_sum)

# Matrix addition
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])
matrix_sum = matrix1 + matrix2
print("Matrix Sum:\n", matrix_sum)

Vector Sum: [5 7 9]
Matrix Sum:
 [[ 8 10 12]
 [14 16 18]]


In [28]:
#Scalar Multiplication
#You can multiply a vector or matrix by a scalar:
# Scalar multiplication
scalar = 2
vector = [1,2,3]
vector_scaled = scalar * vector
print("Scaled Vector:", vector_scaled)

matrix=np.array([[1,2],[3,4]])

matrix_scaled = scalar * matrix
print("Scaled Matrix:\n", matrix_scaled)

Scaled Vector: [1, 2, 3, 1, 2, 3]
Scaled Matrix:
 [[2 4]
 [6 8]]


In [34]:
#Element-wise Multiplication
#Element-wise multiplication between vectors or matrices can be done using the * operator:
#Element-wise multiplication
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

elementwise_product = vector1 * vector2
print("Element-wise Product:", elementwise_product)

matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
matrix_product = matrix1 * matrix2
print("Element-wise Matrix Product:\n", matrix_product)

Element-wise Product: [ 4 10 18]
Element-wise Matrix Product:
 [[ 5 12]
 [21 32]]


NumPy Matrix Operations
Here are some of the basic matrix operations provided by NumPy.

Functions-	Descriptions
array() -   creates a matrix
dot()	-   performs matrix multiplication 
transpose()-transposes a matrix 
linalg.inv()-calculates the inverse of a matrix
linalg.det()-calculates the determinant of a matrix
flatten()- 	 transforms a matrix into 1D array

In [13]:
matrix1=np.array([[1,2],[3,4]]) 


matrix2=np.array([[5,6],[7,8]])

#to multipy using dot

result= np.dot(matrix1 ,matrix2)
print("Matrix multipication of 2 vectors :  \n " , result)

Matrix multipication of 2 vector :  
  [[19 22]
 [43 50]]


In [19]:
# Transpose NumPy Matrix
print(matrix1)
transpos = np.transpose(matrix1)
print("Transpose of matrix is")
print(transpos)

[[1 2]
 [3 4]]
Transpose of matrix is
[[1 3]
 [2 4]]


In [20]:
# Inverse of a Matrix using numpy
print(matrix1)
inverse = np.linalg.inv(matrix1)
print(inverse)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Note: If we try to find the inverse of a non-square matrix, we will get an error message: numpy.linalg.linalgerror: Last 2 dimensions of the array must be square

#### Determinant of a Matrix in NumPy
We can find the determinant of a square matrix using the np.linalg.det() function to calculate the determinant of the given matrix.


det(A) = ad - bc

In [22]:
newarray=np.array([[0,1],[1,2]])
detresult=np.linalg.det(newarray)
print(detresult)

-1.0


### Flatten Matrix in NumPy
Flattening a matrix simply means converting a matrix into a 1D array.

To flatten a matrix into a 1-D array we use the array.flatten() function.

In [23]:
# create a 2x3 matrix
matrix1 = np.array([[1, 2, 3], [4, 5, 7]])

result = matrix1.flatten()
print("Flattened 2x3 matrix:", result)

Flattened 2x3 matrix: [1 2 3 4 5 7]
